"""Write the CV's publication list as LaTeX from _data/publications.yml.

Usage:
    python scripts/make_cv_publications.py path/to/publications.tex

The CV's main.tex does \\input{publications} in its preamble, then uses
\\pubsummary (one line: counts, citations and h-index) and \\publist (the full list,
numbered down to 1 in each group). main.tex defines \\cvsubsection and \\pub.
.github/workflows/update-cv.yml runs this before compiling the CV, so the
CV's publications follow the ADS library the same way the website does.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PUBS = ROOT / "_data" / "publications.yml"
CITES = ROOT / "_data" / "citations.yml"
GREEK = {c: rf"$\{n}$" for c, n in zip(
    "αβγδεζηθικλμνξοπρςστυφχψω",
    "alpha beta gamma delta epsilon zeta eta theta iota kappa lambda mu nu xi o pi rho "
    "varsigma sigma tau upsilon phi chi psi omega".split())} | {"ο": "o"}
LIBRARY = "https://ui.adsabs.harvard.edu/public-libraries/8zUtfV-GT9KVqGIFMyOYVw"


def read_yaml_list(path):
    """Read the simple list-of-dicts YAML written by update_publications.py."""
    items = []
    for line in path.read_text().splitlines():
        m = re.match(r"^(- |  )(\w+): (.*)$", line)
        if not m:
            continue
        if m.group(1) == "- ":
            items.append({})
        items[-1][m.group(2)] = json.loads(m.group(3))
    return items


def tex(s):
    s = str(s)
    for a, b in [("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
                 ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"),
                 ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}")]:
        s = s.replace(a, b)
    s = s.replace(r"\textbackslash\{\}", r"\textbackslash{}")
    return re.sub("[α-ω]", lambda m: GREEK[m.group()], s)


JOURNALS = {"ApJ": "The Astrophysical Journal", "ApJS": "The Astrophysical Journal Supplement Series",
            "ApJL": "The Astrophysical Journal Letters", "AJ": "The Astronomical Journal",
            "MNRAS": "Monthly Notices of the Royal Astronomical Society",
            "A&A": "Astronomy and Astrophysics", "PASP": "Publications of the Astronomical Society of the Pacific"}


def authors(p):
    """First three authors, plus A. Laroche if later in the list, then et al."""
    names = re.sub(r",? et al\..*$", "", p["authors"]).split(", ")
    me = next(i for i, n in enumerate(names) if n.startswith("**"))
    many = len(names) > 5 or "et al." in p["authors"]
    shown = names[:3] if many else names
    if many and me >= 3:
        shown.append(names[me])
    text = tex(", ".join(shown) + (", et al." if many else ""))
    return re.sub(r"\*\*(.+?)\*\*", r"\\textbf{\1}", text)


def venue(p):
    m = re.match(r"^(\S+) (\d+), (\S+)(.*)$", p["venue"])
    if m and m.group(1) in JOURNALS:
        return f"{JOURNALS[m.group(1)]}, {m.group(2)}, {m.group(3)}{m.group(4)}"
    return p["venue"]


def entry(n, p):
    link = p.get("doi") or p.get("arxiv") or p["ads"]
    return (rf"\pub{{{n}}}{{{authors(p)} ({p['year']})}}{{{tex(p['title'])}}}"
            rf"{{\href{{{link}}}{{{tex(venue(p))}}}}}")


def h_index(pubs):
    cites = sorted((p["citations"] for p in pubs), reverse=True)
    return sum(c >= i + 1 for i, c in enumerate(cites))


def main(out):
    pubs = read_yaml_list(PUBS)
    groups = [
        ("Lead-Author Publications", [p for p in pubs if p["first_author"] and not p["conference"]]),
        ("Co-Authored Publications", [p for p in pubs if not p["first_author"] and not p["conference"]]),
        ("Other Publications", [p for p in pubs if p["conference"]]),
    ]
    papers = [p for p in pubs if not p["conference"]]
    first = sum(p["first_author"] for p in papers)
    lines = ["% Generated by scripts/make_cv_publications.py in alexanderlaroche.github.io",
             "% from the ADS library. Do not edit by hand; changes are overwritten weekly."]
    summary = f"{len(papers)} papers, {first} as lead author"
    if CITES.exists():
        total = sum(c["citations"] for c in read_yaml_list(CITES))
        summary += f"; {total} citations"
    summary += f"; $h$-index $= {h_index(pubs)}$"
    lines.append(rf"\newcommand{{\pubsummary}}{{{summary} (\href{{{LIBRARY}}}{{ADS Library}})}}")
    lines.append(r"\newcommand{\publist}{%")
    for title, items in groups:
        if not items:
            continue
        lines.append(rf"\cvsubsection{{{title}}}")
        lines += [entry(len(items) - i, p) for i, p in enumerate(items)]
    lines.append("}")
    Path(out).write_text("\n".join(lines) + "\n")
    print(f"Wrote {out}: {summary}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "publications.tex")
