"""Write the CV's publication list as LaTeX from _data/publications.yml.

Usage:
    python scripts/make_cv_publications.py path/to/publications.tex

The CV's main.tex does \\input{publications} in its preamble, then uses
\\pubsummary (one line: counts, citations and h-index) and \\publist (the full list,
numbered down to 1 in each group). main.tex defines \\cvsubsection and \\pub.
.github/workflows/update-cv.yml runs this before compiling the CV, so the
CV's publications follow the ADS library the same way the website does.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PUBS = ROOT / "_data" / "publications.yml"
CITES = ROOT / "_data" / "citations.yml"
METRICS = ROOT / "_data" / "ads_metrics.yml"
GREEK = {c: rf"$\{n}$" for c, n in zip(
    "αβγδεζηθικλμνξοπρςστυφχψω",
    "alpha beta gamma delta epsilon zeta eta theta iota kappa lambda mu nu xi o pi rho "
    "varsigma sigma tau upsilon phi chi psi omega".split())} | {"ο": "o"}
LIBRARY = "https://ui.adsabs.harvard.edu/public-libraries/8zUtfV-GT9KVqGIFMyOYVw"


def read_yaml_list(path):
    """Read the simple list-of-dicts YAML written by update_publications.py."""
    items = []
    for line in path.read_text().splitlines():
        m = re.match(r"^(- |  )(\w+): (.*)$", line)
        if not m:
            continue
        if m.group(1) == "- ":
            items.append({})
        items[-1][m.group(2)] = json.loads(m.group(3))
    return items


def tex(s):
    s = str(s)
    for a, b in [("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
                 ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"),
                 ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}")]:
        s = s.replace(a, b)
    s = s.replace(r"\textbackslash\{\}", r"\textbackslash{}")
    return re.sub("[α-ω]", lambda m: GREEK[m.group()], s)


JOURNALS = {"ApJ": "The Astrophysical Journal", "ApJS": "The Astrophysical Journal Supplement Series",
            "ApJL": "The Astrophysical Journal Letters", "AJ": "The Astronomical Journal",
            "MNRAS": "Monthly Notices of the Royal Astronomical Society",
            "A&A": "Astronomy and Astrophysics", "PASP": "Publications of the Astronomical Society of the Pacific"}


def authors(p):
    """First authors, then et al.: up to A. Laroche if in the top four, else the first three.

    Never skip names before A. Laroche, so the author position reads correctly.
    """
    full = p["authors"]
    names = re.sub(r",? et al\..*$", "", full).split(", ")
    me = next(i for i, n in enumerate(names) if n.startswith("**"))
    total = int(m.group(1)) if (m := re.search(r"\((\d+) authors\)", full)) else len(names)
    shown = names[:max(me + 1, 3)] if me < 4 else names[:3]
    text = ", ".join(shown) + (", et al." if total > len(shown) else "")
    return re.sub(r"\*\*(.+?)\*\*", r"\\textbf{\1}", tex(text))


def venue(p):
    m = re.match(r"^(\S+) (\d+), (\S+)(.*)$", p["venue"])
    if m and m.group(1) in JOURNALS:
        return f"{JOURNALS[m.group(1)]}, {m.group(2)}, {m.group(3)}{m.group(4)}"
    return p["venue"]


def entry(n, p):
    link = p.get("doi") or p.get("arxiv") or p["ads"]
    return (rf"\pub{{{n}}}{{{authors(p)} ({p['year']})}}{{{tex(p['title'])}}}"
            rf"{{\href{{{link}}}{{{tex(venue(p))}}}}}")


def h_index(pubs):
    """ADS's h-index for the library if update_publications.py saved it, else from our counts."""
    if METRICS.exists():
        m = re.search(r"^h_index: (\d+)", METRICS.read_text(), re.M)
        if m:
            return int(m.group(1))
    cites = sorted((p["citations"] for p in pubs), reverse=True)
    return sum(c >= i + 1 for i, c in enumerate(cites))


def position(p):
    """0 for lead author, 1 for second author, and so on."""
    return next(i for i, n in enumerate(p["authors"].split(", ")) if n.startswith("**"))


def main(out):
    pubs = read_yaml_list(PUBS)
    groups = [
        ("First-Author Publications", [p for p in pubs if position(p) == 0 and not p["conference"]]),
        ("Second- and Third-Author Publications", [p for p in pubs if position(p) in (1, 2) and not p["conference"]]),
        ("Contributing-Author Publications", [p for p in pubs if position(p) > 2 and not p["conference"]]),
        ("Other Publications", [p for p in pubs if p["conference"]]),
    ]
    papers = [p for p in pubs if not p["conference"]]
    first = sum(position(p) == 0 for p in papers)
    second = sum(position(p) in (1, 2) for p in papers)
    lines = ["% Generated by scripts/make_cv_publications.py in alexanderlaroche.github.io",
             "% from the ADS library. Do not edit by hand; changes are overwritten weekly."]
    summary = f"{len(papers)} papers, {first} as first author, {second} as second or third author"
    if CITES.exists():
        total = sum(c["citations"] for c in read_yaml_list(CITES))
        summary += f"; {total} citations"
    summary += f"; $h$-index $= {h_index(pubs)}$"
    lines.append(rf"\newcommand{{\pubsummary}}{{{summary} (\href{{{LIBRARY}}}{{ADS Library}})}}")
    lines.append(r"\newcommand{\publist}{%")
    for title, items in groups:
        if not items:
            continue
        lines.append(rf"\cvsubsection{{{title}}}")
        lines += [entry(len(items) - i, p) for i, p in enumerate(items)]
    lines.append("}")
    Path(out).write_text("\n".join(lines) + "\n")
    print(f"Wrote {out}: {summary}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "publications.tex")
